FLAG = -Wall -Werror -g

v1: reverse-v1.c
	gcc -o reverse reverse-v1.c $(FLAG)

v2: reverse-v2.c
	gcc -o reverse reverse-v2.c $(FLAG)

v3: reverse-v3.c
	gcc -o reverse reverse-v3.c $(FLAG)

v4: reverse-v4.c
	gcc -o reverse reverse-v4.c $(FLAG)

v5: reverse-v5.c
	gcc -o reverse reverse-v5.c $(FLAG)

v6: reverse-v6.c
	gcc -o reverse reverse-v6.c $(FLAG)

v7: reverse-v7.c
	gcc -o reverse reverse-v7.c $(FLAG)

